// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActionMenuController from "./action_menu_controller"
application.register("action-menu", ActionMenuController)

import BulkImportController from "./bulk_import_controller"
application.register("bulk-import", BulkImportController)

import CopyController from "./copy_controller"
application.register("copy", CopyController)

import DrilldownController from "./drilldown_controller"
application.register("drilldown", DrilldownController)

import FiltersController from "./filters_controller"
application.register("filters", FiltersController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MaskingController from "./masking_controller"
application.register("masking", MaskingController)

import MultiselectController from "./multiselect_controller"
application.register("multiselect", MultiselectController)

import NotesController from "./notes_controller"
application.register("notes", NotesController)

import PaginationController from "./pagination_controller"
application.register("pagination", PaginationController)

import SessionFiltersController from "./session_filters_controller"
application.register("session-filters", SessionFiltersController)

import SeverityController from "./severity_controller"
application.register("severity", SeverityController)

import TagsController from "./tags_controller"
application.register("tags", TagsController)
