development:
  adapter: redis
  url: "redis://redis:6379/1"
  channel_prefix: simmer_development


test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://#{ENV.fetch('REDIS_HOST', 'redis')}:6379/1" } %>
  channel_prefix: sim_production
