name: Brakeman Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  brakeman-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Brakeman Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Ruby - use the latest stable Ruby version (3.2.x)
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true  # Enables caching of gems for better performance

      # Install Brakeman - latest stable version (currently 5.x+)
      - name: Setup Brakeman
        env:
          BRAKEMAN_VERSION: '5.3.1' # Update to the latest stable Brakeman version
        run: |
          gem install brakeman --version $BRAKEMAN_VERSION

      # Run Brakeman scan and generate SARIF report
      - name: Brakeman Scan
        continue-on-error: true
        run: |
          brakeman -f sarif -o output.sarif.json .

      # Upload SARIF report for GitHub's security scanning
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: output.sarif.json
